#!/usr/bin/env bash
set -euf -o pipefail

node_modules/.bin/sanctuary-prepublish "$@"

bin/transcribe \
  --url "https://github.com/plaid/transcribe/blob/v$VERSION/{filename}#L{line}" \
  -- examples/fp.js >examples/fp.md
git add examples/fp.md
